export const MOCK_USER = {
  student: {
    id: 'u_stu_001',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@dtep.edu',
    role: 'student',
    avatarInitials: 'AS',
    program: 'B.Tech Computer Science, Semester 6',
    enrolledSince: 'Aug 2023',
    stats: {
      testsTaken: 24,
      avgScore: 82.4,
      percentile: 87,
      streak: 12,
    },
  },
  evaluator: {
    id: 'u_eva_001',
    name: 'Dr. Priya Natarajan',
    email: 'priya.natarajan@dtep.edu',
    role: 'evaluator',
    avatarInitials: 'PN',
    department: 'Department of Computer Science',
    title: 'Senior Evaluator',
    stats: {
      testsCreated: 58,
      submissionsGraded: 1247,
      avgTurnaround: '1.4 days',
      activeClasses: 6,
    },
  },
  admin: {
    id: 'u_adm_001',
    name: 'Daniel Ortiz',
    email: 'daniel.ortiz@dtep.edu',
    role: 'admin',
    avatarInitials: 'DO',
    title: 'Director of Assessments',
    org: 'DTEP University',
    stats: {
      activeEvaluators: 42,
      registeredStudents: 2841,
      testsThisSemester: 184,
      avgCompletion: 94.2,
    },
  },
}

export const SUBJECTS = [
  { id: 'cs301', name: 'Data Structures & Algorithms', code: 'CS-301', color: 'olive' },
  { id: 'cs302', name: 'Database Management Systems', code: 'CS-302', color: 'terracotta' },
  { id: 'cs303', name: 'Operating Systems', code: 'CS-303', color: 'charcoal' },
  { id: 'cs304', name: 'Computer Networks', code: 'CS-304', color: 'olive' },
  { id: 'ma201', name: 'Discrete Mathematics', code: 'MA-201', color: 'beige' },
  { id: 'cs305', name: 'Machine Learning Fundamentals', code: 'CS-305', color: 'terracotta' },
]

export const MOCK_QUESTIONS = {
  cs301_midterm: [
    {
      id: 'q1',
      number: 1,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Trees',
      text: 'Which of the following tree traversals visits nodes in the order: left subtree, root, right subtree?',
      options: [
        { key: 'A', label: 'Preorder traversal' },
        { key: 'B', label: 'Inorder traversal' },
        { key: 'C', label: 'Postorder traversal' },
        { key: 'D', label: 'Level-order traversal' },
      ],
      correctKey: 'B',
      explanation: 'Inorder traversal follows the pattern: Left → Root → Right. For BSTs, this yields nodes in sorted order.',
    },
    {
      id: 'q2',
      number: 2,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Hashing',
      text: 'A hash table of size 10 uses the hash function h(k) = k mod 10 and linear probing. Keys 12, 22, 32, 42 are inserted in that order. At which index is key 42 stored?',
      options: [
        { key: 'A', label: 'Index 2' },
        { key: 'B', label: 'Index 3' },
        { key: 'C', label: 'Index 4' },
        { key: 'D', label: 'Index 5' },
      ],
      correctKey: 'D',
      explanation: '12→2, 22→3 (collision), 32→4 (collision×2), 42→5 (collision×3). Linear probing probes sequentially from h(k).',
    },
    {
      id: 'q3',
      number: 3,
      type: 'mcq',
      marks: 3,
      subject: 'DSA',
      chapter: 'Sorting',
      text: 'Given an array of N integers already sorted in ascending order, which sorting algorithm exhibits the WORST (highest) asymptotic time complexity?',
      options: [
        { key: 'A', label: 'Insertion Sort' },
        { key: 'B', label: 'Merge Sort' },
        { key: 'C', label: 'QuickSort (first element as pivot)' },
        { key: 'D', label: 'Bubble Sort with early exit' },
      ],
      correctKey: 'C',
      explanation: 'With the first element as pivot on a sorted array, QuickSort degenerates to O(N²). The first three choices give O(N), O(N log N), and O(N) respectively.',
    },
    {
      id: 'q4',
      number: 4,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Graphs',
      text: 'Which of the following statements about BFS and DFS on an unweighted connected graph is TRUE?',
      options: [
        { key: 'A', label: 'DFS always finds the shortest path between two nodes' },
        { key: 'B', label: 'BFS always finds the shortest path between two nodes' },
        { key: 'C', label: 'Both BFS and DFS always find the shortest path' },
        { key: 'D', label: 'Neither BFS nor DFS can find the shortest path' },
      ],
      correctKey: 'B',
      explanation: 'On unweighted graphs, BFS explores nodes level-by-level and is guaranteed to find the shortest path in terms of edge count.',
    },
    {
      id: 'q5',
      number: 5,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Dynamic Programming',
      text: 'The bottom-up approach to dynamic programming is BEST described as:',
      options: [
        { key: 'A', label: 'Recursively solving the largest subproblem first, then smaller ones' },
        { key: 'B', label: 'Solving the smallest subproblems first and building up' },
        { key: 'C', label: 'Randomly selecting subproblems to solve until the target is reached' },
        { key: 'D', label: 'Using a greedy strategy with backtracking' },
      ],
      correctKey: 'B',
      explanation: 'Bottom-up (tabular) DP iteratively solves subproblems in order of increasing size, storing results so each larger problem reuses previously computed answers.',
    },
    {
      id: 'q6',
      number: 6,
      type: 'mcq',
      marks: 3,
      subject: 'DSA',
      chapter: 'Complexity',
      text: 'Three algorithms have runtimes: A = O(n log n), B = O(n²), C = O(2ⁿ). For sufficiently large n, which order is correct from fastest to slowest?',
      options: [
        { key: 'A', label: 'A, B, C' },
        { key: 'B', label: 'B, A, C' },
        { key: 'C', label: 'C, A, B' },
        { key: 'D', label: 'A, C, B' },
      ],
      correctKey: 'A',
      explanation: 'Polylogarithmic (n log n) grows slowest, then polynomial (n²), then exponential (2ⁿ). By L&apos;Hôpital, n log n / n² → 0 and n² / 2ⁿ → 0 as n → ∞.',
    },
    {
      id: 'q7',
      number: 7,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Stacks & Queues',
      text: 'A queue implemented using two stacks supports enqueue and dequeue in which amortized time complexity?',
      options: [
        { key: 'A', label: 'O(1) enqueue, O(1) dequeue' },
        { key: 'B', label: 'O(1) enqueue, O(n) worst-case dequeue but O(1) amortized' },
        { key: 'C', label: 'O(n) enqueue, O(n) dequeue' },
        { key: 'D', label: 'O(log n) enqueue, O(log n) dequeue' },
      ],
      correctKey: 'B',
      explanation: 'Enqueue onto stack 1 (O(1)). Dequeue from stack 2; if empty, pour all elements from stack 1. Each element moves at most twice overall, giving O(1) amortized dequeue.',
    },
    {
      id: 'q8',
      number: 8,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Trees',
      text: 'An AVL tree is a BST with a height-balance invariant. After an insertion that violates the invariant, the required number of rotations (single or double) to restore balance is at most:',
      options: [
        { key: 'A', label: '0' },
        { key: 'B', label: '1' },
        { key: 'C', label: '2' },
        { key: 'D', label: 'O(log n)' },
      ],
      correctKey: 'C',
      explanation: 'AVL trees only ever require at most one single rotation or one double rotation (two single rotations) at the deepest unbalanced ancestor — never more, because insertion changes height by at most 1.',
    },
    {
      id: 'q9',
      number: 9,
      type: 'mcq',
      marks: 3,
      subject: 'DSA',
      chapter: 'Strings',
      text: 'The KMP pattern-matching algorithm preprocesses the pattern of length M in O(M) time. Its running time on a text of length N is:',
      options: [
        { key: 'A', label: 'O(N + M)' },
        { key: 'B', label: 'O(N × M)' },
        { key: 'C', label: 'O(N log M)' },
        { key: 'D', label: 'O(M log N)' },
      ],
      correctKey: 'A',
      explanation: 'KMP uses the failure function (longest prefix-suffix) to skip characters it already knows match, so each text pointer advance is monotonic, yielding overall O(N + M).',
    },
    {
      id: 'q10',
      number: 10,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Heaps',
      text: 'Building a binary min-heap from an unsorted array of N elements using Floyd&apos;s algorithm (bottom-up heapify) has time complexity:',
      options: [
        { key: 'A', label: 'O(N log N)' },
        { key: 'B', label: 'O(N)' },
        { key: 'C', label: 'O(N²)' },
        { key: 'D', label: 'O(log N)' },
      ],
      correctKey: 'B',
      explanation: 'Floyd&apos;s method heapifies subtrees from the leaves upward. Summing heights × node counts yields Σ h·⌈N/2ʰ⁺¹⌉ ≤ N·Σ h/2ʰ = O(N).',
    },
    {
      id: 'q11',
      number: 11,
      type: 'mcq',
      marks: 2,
      subject: 'DSA',
      chapter: 'Recursion',
      text: 'The recurrence T(n) = 2T(n/2) + n, with T(1) = 1, solves asymptotically to:',
      options: [
        { key: 'A', label: 'O(n)' },
        { key: 'B', label: 'O(n log n)' },
        { key: 'C', label: 'O(n²)' },
        { key: 'D', label: 'O(log n)' },
      ],
      correctKey: 'B',
      explanation: 'Case 2 of the Master Theorem: a = bᵏ since 2 = 2¹ and f(n) = Θ(n log⁰ n). Hence T(n) = Θ(n log n).',
    },
    {
      id: 'q12',
      number: 12,
      type: 'mcq',
      marks: 3,
      subject: 'DSA',
      chapter: 'Graphs',
      text: 'Kruskal&apos;s minimum spanning tree algorithm processes edges in increasing weight order and uses a Union-Find (Disjoint-Set Union) data structure. Its runtime with union by rank and path compression is:',
      options: [
        { key: 'A', label: 'O(V²)' },
        { key: 'B', label: 'O(E log E)' },
        { key: 'C', label: 'O(E + V log V)' },
        { key: 'D', label: 'O(E · α(V))' },
      ],
      correctKey: 'B',
      explanation: 'Sorting E edges dominates at O(E log E). The Union-Find operations add O(E · α(V)), negligible compared to sorting. Option C is Prim with a Fibonacci heap.',
    },
  ],
}

export const MOCK_TESTS = {
  upcoming: [
    {
      id: 't_cs301_mid',
      title: 'Midterm Examination: Data Structures & Algorithms',
      subject: SUBJECTS[0],
      duration: 90,
      totalMarks: 60,
      totalQuestions: 25,
      scheduledAt: 'Jul 05, 2026 · 09:30 AM',
      windowCloses: 'Jul 05, 2026 · 12:30 PM',
      status: 'upcoming',
      instructions: 'Closed-book. No external calculators or references. One question at a time. Questions cannot be skipped without saving.',
      proctoring: 'AI Proctoring: Screen share, tab-switch detection',
    },
    {
      id: 't_cs304_mid',
      title: 'Quiz 2 — Transport Layer & Congestion Control',
      subject: SUBJECTS[3],
      duration: 45,
      totalMarks: 25,
      totalQuestions: 18,
      scheduledAt: 'Jul 08, 2026 · 02:00 PM',
      windowCloses: 'Jul 08, 2026 · 04:00 PM',
      status: 'upcoming',
      instructions: 'Open notes permitted. Calculator allowed. 1 attempt allowed.',
      proctoring: 'Lightweight proctoring — identity verified only',
    },
  ],
  active: [
    {
      id: 't_cs302_quiz3',
      title: 'Quiz 3 — Normal Forms & Transactions',
      subject: SUBJECTS[1],
      duration: 40,
      totalMarks: 20,
      totalQuestions: 12,
      startedAt: 'Available now',
      expiresAt: 'Closes in 2 days 4 hours',
      status: 'active',
      instructions: 'Self-paced. Resume anytime before window closes.',
    },
  ],
  completed: [
    {
      id: 't_cs301_quiz2',
      title: 'Quiz 2 — Hashing & Graphs',
      subject: SUBJECTS[0],
      duration: 30,
      totalMarks: 15,
      totalQuestions: 10,
      submittedAt: 'Jun 24, 2026',
      status: 'completed',
      score: 14,
      maxScore: 15,
      percentile: 94,
      gradedBy: 'Auto + Staff Review',
      rank: 12,
      classSize: 184,
    },
    {
      id: 't_ma201_mid',
      title: 'Midterm: Discrete Mathematics',
      subject: SUBJECTS[4],
      duration: 90,
      totalMarks: 60,
      totalQuestions: 24,
      submittedAt: 'Jun 20, 2026',
      status: 'completed',
      score: 54,
      maxScore: 60,
      percentile: 89,
      gradedBy: 'Dr. Kapoor',
      rank: 22,
      classSize: 207,
    },
    {
      id: 't_cs303_quiz1',
      title: 'Quiz 1 — Process Scheduling',
      subject: SUBJECTS[2],
      duration: 25,
      totalMarks: 10,
      totalQuestions: 10,
      submittedAt: 'Jun 14, 2026',
      status: 'completed',
      score: 8.5,
      maxScore: 10,
      percentile: 78,
      gradedBy: 'Auto-graded',
      rank: 48,
      classSize: 176,
    },
    {
      id: 't_cs305_assign',
      title: 'Assignment — Regression Models',
      subject: SUBJECTS[5],
      duration: 180,
      totalMarks: 40,
      totalQuestions: 8,
      submittedAt: 'May 30, 2026',
      status: 'completed',
      score: 37,
      maxScore: 40,
      percentile: 91,
      gradedBy: 'Dr. Singh',
      rank: 15,
      classSize: 142,
    },
  ],
}

export const MOCK_EVALUATOR_TESTS = [
  {
    id: 'e_cs301_mid',
    title: 'Midterm: DSA',
    subject: SUBJECTS[0],
    questions: 25,
    duration: 90,
    totalMarks: 60,
    scheduled: 'Jul 05, 2026 · 09:30 AM',
    status: 'scheduled',
    registration: { enrolled: 184, approved: 172 },
  },
  {
    id: 'e_cs301_quiz2',
    title: 'Quiz 2 — Hashing & Graphs',
    subject: SUBJECTS[0],
    questions: 10,
    duration: 30,
    totalMarks: 15,
    scheduled: 'Jun 24, 2026',
    status: 'graded',
    submissionStats: {
      submitted: 176,
      pendingGrading: 0,
      avgScore: 11.2,
      median: 12,
      max: 15,
      min: 2,
    },
  },
  {
    id: 'e_cs302_quiz3',
    title: 'Quiz 3 — Normal Forms & Transactions',
    subject: SUBJECTS[1],
    questions: 12,
    duration: 40,
    totalMarks: 20,
    scheduled: 'Live now',
    status: 'live',
    registration: { enrolled: 164, started: 91, submitted: 12 },
  },
  {
    id: 'e_ma201_mid',
    title: 'Midterm: Discrete Mathematics',
    subject: SUBJECTS[4],
    questions: 24,
    duration: 90,
    totalMarks: 60,
    scheduled: 'Jun 20, 2026',
    status: 'graded',
    submissionStats: {
      submitted: 198,
      pendingGrading: 0,
      avgScore: 44.6,
      median: 46,
      max: 58,
      min: 12,
    },
  },
]

export const MOCK_SUBMISSIONS = [
  {
    id: 's_001',
    student: {
      name: 'Aarav Sharma',
      roll: 'CS2023-042',
      avatarInitials: 'AS',
    },
    test: {
      title: 'Quiz 2 — Hashing & Graphs',
      subject: SUBJECTS[0],
    },
    submittedAt: 'Jun 24, 2026 · 10:14 AM',
    timeTaken: '26m 42s',
    autoScore: 14,
    maxScore: 15,
    status: 'needs_review',
    flags: ['manual_review'],
    percentile: 94,
  },
  {
    id: 's_002',
    student: {
      name: 'Ishita Verma',
      roll: 'CS2023-118',
      avatarInitials: 'IV',
    },
    test: {
      title: 'Quiz 2 — Hashing & Graphs',
      subject: SUBJECTS[0],
    },
    submittedAt: 'Jun 24, 2026 · 10:21 AM',
    timeTaken: '29m 07s',
    autoScore: 15,
    maxScore: 15,
    status: 'graded',
    percentile: 99,
  },
  {
    id: 's_003',
    student: {
      name: 'Rohan Mehta',
      roll: 'CS2023-227',
      avatarInitials: 'RM',
    },
    test: {
      title: 'Quiz 2 — Hashing & Graphs',
      subject: SUBJECTS[0],
    },
    submittedAt: 'Jun 24, 2026 · 10:08 AM',
    timeTaken: '22m 55s',
    autoScore: 9,
    maxScore: 15,
    status: 'graded',
    percentile: 36,
  },
  {
    id: 's_004',
    student: {
      name: 'Ananya Rao',
      roll: 'CS2023-074',
      avatarInitials: 'AR',
    },
    test: {
      title: 'Midterm: Discrete Mathematics',
      subject: SUBJECTS[4],
    },
    submittedAt: 'Jun 20, 2026 · 11:40 AM',
    timeTaken: '1h 12m',
    autoScore: 44,
    maxScore: 60,
    status: 'needs_review',
    flags: ['answer_dispute', 'tab_switch_detected'],
    percentile: 78,
  },
  {
    id: 's_005',
    student: {
      name: 'Kabir Jain',
      roll: 'CS2023-091',
      avatarInitials: 'KJ',
    },
    test: {
      title: 'Quiz 2 — Hashing & Graphs',
      subject: SUBJECTS[0],
    },
    submittedAt: 'Jun 24, 2026 · 10:11 AM',
    timeTaken: '25m 03s',
    autoScore: 11,
    maxScore: 15,
    status: 'graded',
    percentile: 62,
  },
  {
    id: 's_006',
    student: {
      name: 'Mira Patel',
      roll: 'CS2023-056',
      avatarInitials: 'MP',
    },
    test: {
      title: 'Midterm: DSA',
      subject: SUBJECTS[0],
    },
    submittedAt: 'Jun 16, 2026 · 09:38 AM',
    timeTaken: '1h 25m',
    autoScore: 55,
    maxScore: 60,
    status: 'flagged',
    flags: ['abnormal_response_pattern'],
    percentile: 88,
  },
]

export const MOCK_RUBRIC_QUESTIONS = [
  {
    id: 'rq1',
    number: 1,
    text: 'What is the asymptotic time complexity of binary search on a sorted array?',
    marks: 2,
    difficulty: 'Easy',
    chapter: 'Searching',
    options: [
      { key: 'A', label: 'O(n)' },
      { key: 'B', label: 'O(log n)' },
      { key: 'C', label: 'O(n log n)' },
      { key: 'D', label: 'O(1)' },
    ],
    correctKey: 'B',
  },
  {
    id: 'rq2',
    number: 2,
    text: 'Which of the following is NOT a stable sorting algorithm?',
    marks: 2,
    difficulty: 'Medium',
    chapter: 'Sorting',
    options: [
      { key: 'A', label: 'Merge Sort' },
      { key: 'B', label: 'Bubble Sort' },
      { key: 'C', label: 'Insertion Sort' },
      { key: 'D', label: 'Heap Sort' },
    ],
    correctKey: 'D',
  },
  {
    id: 'rq3',
    number: 3,
    text: 'A complete binary tree with N nodes has a height of floor(log₂ N). For N = 31, height is:',
    marks: 3,
    difficulty: 'Easy',
    chapter: 'Trees',
    options: [
      { key: 'A', label: '3' },
      { key: 'B', label: '4' },
      { key: 'C', label: '5' },
      { key: 'D', label: '6' },
    ],
    correctKey: 'B',
  },
  {
    id: 'rq4',
    number: 4,
    text: 'Dijkstra&apos;s algorithm on a graph with V vertices and E edges using a binary heap has time complexity:',
    marks: 3,
    difficulty: 'Medium',
    chapter: 'Graphs',
    options: [
      { key: 'A', label: 'O(V²)' },
      { key: 'B', label: 'O(V + E)' },
      { key: 'C', label: 'O(E log V)' },
      { key: 'D', label: 'O(V E log V)' },
    ],
    correctKey: 'C',
  },
  {
    id: 'rq5',
    number: 5,
    text: 'Which data structure is most appropriate for implementing a LRU cache with O(1) get/put?',
    marks: 2,
    difficulty: 'Hard',
    chapter: 'Design',
    options: [
      { key: 'A', label: 'Hash map only' },
      { key: 'B', label: 'Doubly linked list only' },
      { key: 'C', label: 'Hash map + doubly linked list' },
      { key: 'D', label: 'Binary search tree' },
    ],
    correctKey: 'C',
  },
]

export function getActiveTestDetail(id) {
  if (id === 't_cs301_mid') {
    return {
      id,
      title: 'Midterm Examination: Data Structures & Algorithms',
      subject: SUBJECTS[0],
      duration: 60,
      totalMarks: 30,
      totalQuestions: MOCK_QUESTIONS.cs301_midterm.length,
      positiveMarking: 1,
      negativeMarking: 0.25,
      instructions: [
        'This test contains 12 multiple-choice questions. All questions are compulsory.',
        'Each correct answer carries the marks indicated. 25% of marks will be deducted for each wrong answer.',
        'You may navigate freely between questions using the palette on the right.',
        'Use Clear Response to remove a selected option — this is counted as an unanswered question.',
        'Save & Next saves the current answer and advances. Submit ends the test immediately.',
      ],
      questions: MOCK_QUESTIONS.cs301_midterm,
    }
  }
  return null
}
