# Generated by Django 5.2.16 on 2026-07-29 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='awarded_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('STARTED', 'Started'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20),
        ),
    ]
